name: flutter_portal
description: flutter_portal
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dio: 3.0.7
  json_annotation: ^2.2.0
  bot_toast: ^3.0.5
  url_launcher: ^5.4.1
  video_player: ^0.10.5
  cry: ^0.1.2
  cached_network_image: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
